bingo/accounts/urls.py
from django.urls import re_path, path
from .views import RegisterView
from django.contrib.auth import views as auth_views
from .forms import LoginForm

app_name = 'accounts'
urlpatterns = [
    path('register/', RegisterView.as_view(), name="register"),
    path('login/',  auth_views.LoginView.as_view(template_name="accounts/login.html", authentication_form=LoginForm), name="login"),
    path('logout/',  auth_views.logout_then_login, name="logout"),
]

bingo/bingo/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('accounts.urls')),
    path('bingo/', include('game.urls')),
]

bingo/game/urls.py
from django.urls import re_path, path
from .views import IndexView

app_name = 'game'
urlpatterns = [
    path('index/', IndexView.as_view(), name="index"),
]

bingo/accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

# Create your models here.

class User(AbstractUser):
    pass

bingo/game/models.py
from django.db import models

# Create your models here.

bingo/accounts/forms.py
from django import forms
from django.forms import ModelForm
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from .models import User

# Registeration form

class RegistrationForm(UserCreationForm):
    class Meta:
        model = User
        fields = ['email', 'password1', 'password2', 'username']

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

class LoginForm(AuthenticationForm):

    class Meta:
        fields = ['username', 'password']

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

bingo/accounts/views.py
from django.shortcuts import render, redirect
from django.views import View
from .forms import RegistrationForm, LoginForm
from django.contrib.auth import authenticate, login

# Create your views here.

class RegisterView(View):

    form_class = RegistrationForm
    template_name = 'accounts/register.html'

    # if the request is a GET request
    def get(self, request):
        # create a blank form
        registration_form = self.form_class()
        return render(request, self.template_name, {'form': registration_form, 'title': 'Register'})

    # if the request is a POST request
    def post(self, request):
        registration_form = self.form_class(request.POST)
        # check if the form is valid
        if registration_form.is_valid():
            registration_form.save()
            return redirect('accounts:login')
        else:
            return render(request,'accounts/register.html', {'form': registration_form, 'title': 'Register'})

#class IndexView(View):
#
#    template_name = 'accounts/index.html'
#
#    def get(self, request):
#        return render(request, self.template_name, {'title': request.user.username})

bingo/game/views.py
from django.shortcuts import render, redirect
from django.views import View

# Create your views here.

class IndexView(View):

    template_name = 'game/index.html'

    def get(self, request):
        return render(request, self.template_name, {'title': request.user.username})

bingo/accounts/templates/accounts/index.html
<!doctype html>
<html>
    <head>
        <title>{{title}}</title>
    </head>
    <body>
        {{user}}
        <a href="{% url 'accounts:logout' %}">Logout</a>
    </body>
</html>

bingo/accounts/templates/accounts/login.html
<!DOCTYPE html>
<html>
    {% load static %}
    <head>
        <link href="{% static 'accounts/css/BG1.css' %}" rel="stylesheet" type="text/css">
        <title>Bingo Sign In</title>
    </head>
    <body>
        <div id="heading">
            <h1>WELCOME TO BINGO</h1>
        </div><h3>Sign In </h3></br>
        <div id="form" method="post">
            <form action="{% url 'accounts:login' %}" method="post">

                {% csrf_token %}
                </br></br>
                {{form.non_field_errors}}
                {{form.username.label_tag}}
                {{form.username.errors}}
                {{form.username}}
                </br></br>
                {{form.password.label_tag}}
                {{form.password.errorr}}
                {{form.password}}
                </br></br>
                <button type="submit">Submit</button>
                </br></br>
<!--                <label for="">User Name</label>
                <input type="textbox"></br></br></br>

                
                <label for="">Password</label>
                <input type="password" name="sign_in_password"></br></br></br>
                <button type="submit">Submit</button>
                </br></br>
-->
            </form>

<hr>

            <a href="{% url 'accounts:register' %}" >Click here to create a new account!</a>
            
            
        </div>

    </body>
</html>

bingo/accounts/templates/accounts/login_.html
<!DOCTYPE html>
<html lang="en">

{% load static %}

<head>

  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="">
  <meta name="author" content="">

  <title>{{title}}</title>

  <!-- Custom fonts for this template-->
  <link href="{% static 'vendor/fontawesome-free/css/all.min.css' %}" rel="stylesheet" type="text/css">
  <link href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i" rel="stylesheet">

  <!-- Custom styles for this template-->
  <link href="{% static 'css/sb-admin-2.min.css' %}" rel="stylesheet">

</head>

<body class="bg-gradient-primary">

  <div class="container">

    <!-- Outer Row -->
    <div class="row justify-content-center">

      <div class="col-xl-10 col-lg-12 col-md-9">

        <div class="card o-hidden border-0 shadow-lg my-5">
          <div class="card-body p-0">
            <!-- Nested Row within Card Body -->
            <div class="row">
              <div class="col-lg-6 d-none d-lg-block bg-login-image"></div>
              <div class="col-lg-6">
                <div class="p-5">
                  <div class="text-center">
                    <h1 class="h4 text-gray-900 mb-4">Welcome Back!</h1>
                  </div>
                  {% if errors %}
                    {{errors}}
                  {% endif %}
                  <form class="user" method="post" action="{% url 'accounts:login' %}">
                      {% csrf_token %}
                      {{form.non_field_errors}}
                    <div class="form-group">
                        {{form.username.errors}}
                        {{form.username}}
                    </div>
                    <div class="form-group">
                        {{form.password.errors}}
                        {{form.password}}
                    </div>
                    <input type="submit" class="btn btn-primary btn-user btn-block" value="Login"/>
                    <hr>
                    <a href="index.html" class="btn btn-google btn-user btn-block">
                      <i class="fab fa-google fa-fw"></i> Login with Google
                    </a>
                    <a href="index.html" class="btn btn-facebook btn-user btn-block">
                      <i class="fab fa-facebook-f fa-fw"></i> Login with Facebook
                    </a>
                  </form>
                  <hr>
                  <div class="text-center">
                    <a class="small" href="forgot-password.html">Forgot Password?</a>
                  </div>
                  <div class="text-center">
                      <a class="small" href="{% url 'accounts:register' %}">Create an Account!</a>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>

      </div>

    </div>

  </div>

  <!-- Bootstrap core JavaScript-->
  <script src="{% static 'vendor/jquery/jquery.min.js' %}"></script>
  <script src="{% static 'vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>

  <!-- Core plugin JavaScript-->
  <script src="{% static 'vendor/jquery-easing/jquery.easing.min.js' %}"></script>

  <!-- Custom scripts for all pages-->
  <script src="{% static 'js/sb-admin-2.min.js' %}"></script>

</body>

</html>

bingo/accounts/templates/accounts/register.html
<!DOCTYPE html>
<html lang="en">
{% load static %}
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <meta name="description" content="">
        <meta name="author" content="">
        <title>Bingo Register</title>
        <link href="{% static 'accounts/css/BG1.css' %}" rel="stylesheet" type="text/css">
    </head>
    <body>
        <div id="heading">
            <h1>WELCOME TO BINGO</h1>
        </div><h3>Sign Up Here</h3></br>
        <div id="form">
            <form action="{% url 'accounts:register' %}" method="post">
<!--                </br></br>
                <label for="">User Name</label>
                <input type="text" name="username"></br></br></br>

                <label for="">Email ID</label>
                <input type="email" name="email"></br></br></br>
                <label for="">Create Password</label>
                <input type="password" name="password_1"></br></br></br>
                <label for="">Confirm Password</label>
                <input type="password" type="password_2"></br></br></br>
                <button type="submit">Submit</button>
                </br></br>
-->
                </br>
                </br>
                {% csrf_token %}
                {{form.non_field_errors}}
                {{form.email.label_tag}}
                {{form.email.errors}}
                {{form.email}}
                </br>
                </br>
                {{form.username.label_tag}}
                {{form.username.errors}}
                {{form.username}}
                </br>
                </br>
                {{form.password1.label_tag}}
                {{form.password1.errors}}
                {{form.password1}}
                </br>
                </br>
                {{form.password2.label_tag}}
                {{form.password2.errors}}
                {{form.password2}}
                </br>
                </br>
                <button type='submit'>Submit</button>
                </br>
                </br>

            </form>

            <a href="{%url 'accounts:login' %}" >Already have an account! Click here to login!</a>

            
            
        </div>

    </body>
</html>

bingo/accounts/templates/accounts/register_.html
<!DOCTYPE html>
<html lang="en">

{% load static %}

<head>

  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="">
  <meta name="author" content="">

  <title>{{title}}</title>

  <!-- Custom fonts for this template-->
  <link href="{% static 'vendor/fontawesome-free/css/all.min.css' %}" rel="stylesheet" type="text/css">
  <link href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i" rel="stylesheet">

  <!-- Custom styles for this template-->
  <link href="{% static 'css/sb-admin-2.min.css' %}" rel="stylesheet">

</head>

<body class="bg-gradient-primary">

  <div class="container">

    <div class="card o-hidden border-0 shadow-lg my-5">
      <div class="card-body p-0">
        <!-- Nested Row within Card Body -->
        <div class="row">
          <div class="col-lg-5 d-none d-lg-block bg-register-image"></div>
          <div class="col-lg-7">
            <div class="p-5">
              <div class="text-center">
                <h1 class="h4 text-gray-900 mb-4">Create an Account!</h1>
              </div>
              <form class="user" method="post" action="{% url 'accounts:register' %}">
                  {% csrf_token %}
                  {{form.non_field_errors}}
                <div class="form-group row">
                  {{form.first_name.errors}}
                  {{form.last_name.errors}}
                </div>
                <div class="form-group row">
                  <div class="col-sm-6 mb-3 mb-sm-0">
                      {{form.first_name}}
                  </div>
                  <div class="col-sm-6">
                      {{form.last_name}}
                  </div>
                </div>
                <div class="form-group row">
                  {{form.email.errors}}
                  {{form.username.errors}}
                </div>
                <div class="form-group row">
                  <div class="col-sm-6 mb-3 mb-sm-0">
                      {{form.email}}
                  </div>
                  <div class="col-sm-6">
                      {{form.username}}
                  </div>
                </div>
                <div class="form-group row">
                  {{form.password1.errors}}
                  {{form.password2.errors}}
                </div>
                <div class="form-group row">
                  <div class="col-sm-6 mb-3 mb-sm-0">
                      {{form.password1}}
                  </div>
                  <div class="col-sm-6">
                      {{form.password2}}
                  </div>
                </div>
                <input type='submit' class="btn btn-primary btn-user btn-block" value="Register Account"/>
                <hr>
                <a href="index.html" class="btn btn-google btn-user btn-block">
                  <i class="fab fa-google fa-fw"></i> Register with Google
                </a>
                <a href="index.html" class="btn btn-facebook btn-user btn-block">
                  <i class="fab fa-facebook-f fa-fw"></i> Register with Facebook
                </a>
              </form>
              <hr>
              <div class="text-center">
                <a class="small" href="forgot-password.html">Forgot Password?</a>
              </div>
              <div class="text-center">
                <a class="small" href="login.html">Already have an account? Login!</a>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>

  </div>

  <!-- Bootstrap core JavaScript-->
  <script src="{% static 'vendor/jquery/jquery.min.js' %}"></script>
  <script src="{% static 'vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>

  <!-- Core plugin JavaScript-->
  <script src="{% static 'vendor/jquery-easing/jquery.easing.min.js' %}"></script>

  <!-- Custom scripts for all pages-->
  <script src="{% static 'js/sb-admin-2.min.js' %}"></script>

</body>

</html>

bingo/game/templates/game/index.html
<html>
    <head>
        {% load static %}
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">

        <link href="{% static 'game/css/BG2.css' %}" rel="stylesheet" type="text/css">
        <title>Bingo</title>
        
    </head>
    <body>
        <div id="container">
            <div class="row">
                <div id="name" class="col">
                    <h1>{{user}}</h1>
                </div>
                <div id="bingo" class="col">
                    <h1 class="display-1 font-weight-normal">BINGO</h1>
                </div>
                <div id="number " class="col">
                    <div class="w-100 text-right">
                        <span >Next Number</span>
                        <span class="p-5">1</span>
                    </div>
                </div>
            </div>
        </div>
        <div id="table">
        <table>
            <tr>
                <td></td><td></td><td></td><td></td><td></td><th>B</th>
            </tr>
            <tr>
                <td></td><td></td><td></td><td></td><td></td><th>I</th>
            </tr>
            <tr>
                <td></td><td></td><td></td><td></td><td></td><th>N</th>
            </tr>
            <tr>
                <td></td><td></td><td></td><td></td><td></td><th>G</th>
            </tr>
            <tr>
                <td></td><td></td><td></td><td></td><td></td><th>O</th>
            </tr>
        </table>

        </div>
        
        <div id="players">
            <table>
                <tr>
                    <td>1</td><td>11</td>
                </tr>
                <tr>
                    <td>11</td><td>1</td>
                </tr>
                <tr>
                    <td>11</td><td>1</td>

                </tr>
                <tr>
                    <td>1</td>
                    <td>1</td>
                </tr>
                <tr>
                    <td>1</td><td>1</td>
                </tr>
                <tr>
                    <td>11</td><td>1</td>
                </tr>
            </table>
        </div>
    </body>
        
    
</html>